import { useEffect, useState } from 'react'
import { Link, Navigate, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom'
import { AlertTriangle, BarChart3, CheckCircle2, ClipboardCheck, ClipboardList, FileText, LogOut, Menu, Plus, Search, Settings, Shield, User, Users } from 'lucide-react'
import { useToast } from './state/ToastProvider.jsx'

const STORAGE_KEYS = {
  currentUser: 'bob_demo_current_user',
  assignments: 'bob_demo_assignments',
  officers: 'bob_demo_officers',
  assignmentUpdates: 'bob_demo_assignment_updates',
  reviews: 'bob_demo_reviews',
}

const STATUS_OPTIONS = ['Assigned', 'In Progress', 'On Site / Examination Ongoing', 'Report Drafting', 'Submitted for Review', 'Under Review', 'Returned for Corrections', 'Resubmitted', 'Approved', 'Completed', 'Overdue', 'Blocked']
const OFFICER_UPDATE_STATUSES = ['In Progress', 'On Site / Examination Ongoing', 'Report Drafting', 'Submitted for Review', 'Blocked']
const ASSIGNMENT_TYPES = ['Onsite Examination', 'Progress Update', 'Examination Report', 'Memo', 'Letter', 'Presentation', 'Risk Register', 'Meeting Package', 'Governance Report', 'Other']
const PRIORITY_OPTIONS = ['Low', 'Medium', 'High', 'Critical']

const seedOfficers = [
  { id: 'officer-001', name: 'Demo Officer', email: 'officer.demo@bankofbotswana.local', position: 'Compliance Officer', department: 'Compliance' },
  { id: 'officer-002', name: 'Emmanuel Molefe', email: 'emmanuel.demo@bankofbotswana.local', position: 'Senior Compliance Officer', department: 'Compliance' },
  { id: 'officer-003', name: 'Mmapula Motshegare', email: 'mmapula.demo@bankofbotswana.local', position: 'Compliance Officer', department: 'Compliance' },
  { id: 'officer-004', name: 'Oageng Moreputla', email: 'oageng.demo@bankofbotswana.local', position: 'Compliance Analyst', department: 'Compliance' },
  { id: 'officer-005', name: 'Keoage Mongale', email: 'keoage.demo@bankofbotswana.local', position: 'Compliance Officer', department: 'Compliance' },
]

const nowIso = () => new Date().toISOString()

const seedAssignments = [
  { id: 'asg-001', title: 'Orange Money AML/CFT Onsite Examination', description: 'Conduct onsite AML/CFT examination and capture findings for management review.', assignedTo: 'officer-001', assignedBy: 'manager-001', status: 'In Progress', priority: 'High', dueDate: '2026-04-30', assignmentType: 'Onsite Examination', relatedEntity: 'Orange Money Botswana', progressNote: 'Field work ongoing. Draft report expected after onsite review.', createdAt: '2026-04-20T08:30:00.000Z', updatedAt: '2026-04-25T10:45:00.000Z' },
  { id: 'asg-002', title: 'BTC Smega Examination Report', description: 'Finalize examination report and submit for management review.', assignedTo: 'officer-002', assignedBy: 'manager-001', status: 'Submitted for Review', priority: 'High', dueDate: '2026-04-27', assignmentType: 'Examination Report', relatedEntity: 'BTC Smega', progressNote: 'Draft report submitted for management review.', createdAt: '2026-04-18T08:30:00.000Z', updatedAt: '2026-04-26T13:15:00.000Z' },
  { id: 'asg-003', title: 'National Risk Assessment Sensitisation Workshop Slides', description: 'Prepare workshop materials and speaking notes.', assignedTo: 'officer-003', assignedBy: 'manager-001', status: 'In Progress', priority: 'Medium', dueDate: '2026-04-27', assignmentType: 'Presentation', relatedEntity: 'National Risk Assessment', progressNote: 'Presentation slides are being prepared.', createdAt: '2026-04-17T10:00:00.000Z', updatedAt: '2026-04-24T11:00:00.000Z' },
  { id: 'asg-004', title: 'Governance Report for First Quarter', description: 'Develop Q1 governance report with key risk and control updates.', assignedTo: 'officer-004', assignedBy: 'manager-001', status: 'In Progress', priority: 'Medium', dueDate: '2026-05-05', assignmentType: 'Governance Report', relatedEntity: 'Internal', progressNote: 'Drafting in progress.', createdAt: '2026-04-21T09:20:00.000Z', updatedAt: '2026-04-29T15:30:00.000Z' },
  { id: 'asg-005', title: 'BCRCD Risk Register First Quarter', description: 'Compile and validate first-quarter risk register updates.', assignedTo: 'officer-005', assignedBy: 'manager-001', status: 'Submitted for Review', priority: 'Medium', dueDate: '2026-04-25', assignmentType: 'Risk Register', relatedEntity: 'BCRCD', progressNote: 'Submitted to manager for review.', createdAt: '2026-04-12T08:00:00.000Z', updatedAt: '2026-04-25T17:00:00.000Z' },
]

const seedUpdates = {
  'asg-001': [{ id: 'u-1', createdAt: '2026-04-25T10:45:00.000Z', userName: 'Demo Officer', oldStatus: 'Assigned', newStatus: 'In Progress', note: 'Field work ongoing. Draft report expected after onsite review.' }],
  'asg-002': [{ id: 'u-2', createdAt: '2026-04-26T13:15:00.000Z', userName: 'Emmanuel Molefe', oldStatus: 'Report Drafting', newStatus: 'Submitted for Review', note: 'Draft report submitted for management review.' }],
}

function safeParse(value, fallback) { try { const parsed = JSON.parse(value); return parsed ?? fallback } catch { return fallback } }
function getCurrentUser() { return safeParse(localStorage.getItem(STORAGE_KEYS.currentUser), null) }
function setCurrentUser(user) { localStorage.setItem(STORAGE_KEYS.currentUser, JSON.stringify(user)); sessionStorage.setItem(STORAGE_KEYS.currentUser, JSON.stringify(user)) }
function logout() { localStorage.removeItem(STORAGE_KEYS.currentUser); sessionStorage.removeItem(STORAGE_KEYS.currentUser) }
function getAssignments() { return safeParse(localStorage.getItem(STORAGE_KEYS.assignments), []) }
function saveAssignments(assignments) { localStorage.setItem(STORAGE_KEYS.assignments, JSON.stringify(assignments)) }
function createAssignment(data) { const assignments = getAssignments(); const assignment = { ...data, id: `asg-${Date.now()}`, createdAt: nowIso(), updatedAt: nowIso(), status: data.status || 'Assigned' }; assignments.unshift(assignment); saveAssignments(assignments); return assignment }
function updateAssignment(id, changes) { const assignments = getAssignments(); const updated = assignments.map((item) => (item.id === id ? { ...item, ...changes, updatedAt: nowIso() } : item)); saveAssignments(updated); return updated.find((item) => item.id === id) }
function getAssignmentsForOfficer(officerId) { return getAssignments().filter((item) => item.assignedTo === officerId) }
function getOfficers() { return safeParse(localStorage.getItem(STORAGE_KEYS.officers), []) }
function saveOfficers(officers) { localStorage.setItem(STORAGE_KEYS.officers, JSON.stringify(officers)) }
function addOfficer(officer) { const officers = getOfficers(); officers.push(officer); saveOfficers(officers) }
function addAssignmentUpdate(assignmentId, update) { const updates = safeParse(localStorage.getItem(STORAGE_KEYS.assignmentUpdates), {}); const existing = Array.isArray(updates[assignmentId]) ? updates[assignmentId] : []; updates[assignmentId] = [{ id: `upd-${Date.now()}`, createdAt: nowIso(), ...update }, ...existing]; localStorage.setItem(STORAGE_KEYS.assignmentUpdates, JSON.stringify(updates)) }
function getAssignmentUpdates(assignmentId) { const updates = safeParse(localStorage.getItem(STORAGE_KEYS.assignmentUpdates), {}); return Array.isArray(updates[assignmentId]) ? updates[assignmentId] : [] }
function addReview(review) { const reviews = safeParse(localStorage.getItem(STORAGE_KEYS.reviews), []); reviews.unshift({ id: `rev-${Date.now()}`, createdAt: nowIso(), ...review }); localStorage.setItem(STORAGE_KEYS.reviews, JSON.stringify(reviews)) }
function seedDemoData(force = false) { if (force || !localStorage.getItem(STORAGE_KEYS.officers)) saveOfficers(seedOfficers); if (force || !localStorage.getItem(STORAGE_KEYS.assignments)) saveAssignments(seedAssignments); if (force || !localStorage.getItem(STORAGE_KEYS.assignmentUpdates)) localStorage.setItem(STORAGE_KEYS.assignmentUpdates, JSON.stringify(seedUpdates)); if (force || !localStorage.getItem(STORAGE_KEYS.reviews)) localStorage.setItem(STORAGE_KEYS.reviews, JSON.stringify([])) }
function formatDate(dateStr) { return new Date(dateStr).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }) }
function badgeTone(status) { if (['Completed', 'Approved'].includes(status)) return 'success'; if (['Overdue', 'Blocked', 'Returned for Corrections'].includes(status)) return 'danger'; if (['Submitted for Review', 'Under Review', 'Resubmitted'].includes(status)) return 'info'; if (['In Progress', 'On Site / Examination Ongoing', 'Report Drafting'].includes(status)) return 'warning'; return 'neutral' }
function StatusBadge({ status }) { return <span className={`badge badge-${badgeTone(status)}`}>{status}</span> }

function ProtectedRoute({ children }) {
  const location = useLocation()
  const user = getCurrentUser()
  if (!user) return <Navigate to="/login" replace />
  if (user.role === 'officer' && location.pathname.startsWith('/manager')) return <Navigate to="/officer/dashboard" replace />
  if (user.role === 'manager' && location.pathname.startsWith('/officer')) return <Navigate to="/manager/dashboard" replace />
  return children
}

function LoginPage({ onSignedIn }) {
  const navigate = useNavigate()
  const { showToast } = useToast()
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')

  function signInDemo(user) {
    setCurrentUser(user)
    onSignedIn(user)
    showToast({ title: `Signed in as ${user.role}`, message: `${user.name} session started.` })
    navigate(user.role === 'manager' ? '/manager/dashboard' : '/officer/dashboard')
  }

  function submit(event) {
    event.preventDefault()
    if (password !== 'demo123') return showToast({ title: 'Sign in failed', message: 'Use demo credentials. Password: demo123' })
    if (email === 'manager.demo@bankofbotswana.local') return signInDemo({ id: 'manager-001', name: 'Demo Manager', email, role: 'manager', position: 'Manager / Supervisor' })
    if (email === 'officer.demo@bankofbotswana.local') return signInDemo({ id: 'officer-001', name: 'Demo Officer', email, role: 'officer', position: 'Compliance Officer' })
    showToast({ title: 'Sign in failed', message: 'Use manager.demo@bankofbotswana.local or officer.demo@bankofbotswana.local' })
  }

  return <main className="login-screen demo-login"><section className="login-panel demo-login-panel"><div className="login-brand"><div className="seal">BoB</div><div className="bank-title">BANK OF BOTSWANA</div><div className="bank-subtitle">Assignment Management System</div></div><form className="login-form" onSubmit={submit}><span className="login-kicker"><Shield size={15} /> Secure Demo Access</span><h1>Secure Demo Access</h1><p>Sign in to the Assignment Management System.</p><p className="muted-copy">Access is restricted by assigned role. In this demo, use the quick access buttons below to preview the Manager and Officer workflows.</p><label><span>Email</span><input type="email" required value={email} onChange={(e) => setEmail(e.target.value)} /></label><label><span>Password</span><input type="password" required value={password} onChange={(e) => setPassword(e.target.value)} /></label><button className="button primary full" type="submit">Sign in</button><div className="demo-access"><h3>Demo access</h3><div className="two-col-buttons"><button type="button" className="button secondary" onClick={() => signInDemo({ id: 'manager-001', name: 'Demo Manager', email: 'manager.demo@bankofbotswana.local', role: 'manager', position: 'Manager / Supervisor' })}>Continue as Manager</button><button type="button" className="button secondary" onClick={() => signInDemo({ id: 'officer-001', name: 'Demo Officer', email: 'officer.demo@bankofbotswana.local', role: 'officer', position: 'Compliance Officer' })}>Continue as Officer</button></div></div><small className="security-note">Demo environment - role-based access is simulated for presentation. Production deployment would use database-backed authentication and server-side access control.</small></form></section></main>
}

function AppShell({ user, children, items, title, subtitle, onLogout }) {
  const [open, setOpen] = useState(false)
  const navigate = useNavigate()
  const { showToast } = useToast()
  function runLogout() { logout(); showToast({ title: 'Logged out', message: 'Demo session cleared.' }); onLogout(null); navigate('/login') }
  return <div className="app-shell"><div className={`mobile-backdrop ${open ? 'open' : ''}`} onClick={() => setOpen(false)} /><aside className={`sidebar ${open ? 'open' : ''}`}><div className="brand-block"><div className="seal">BoB</div><div className="bank-title">BANK OF BOTSWANA</div><div className="bank-subtitle">Assignment Workflow Demo</div></div><nav className="side-nav">{items.map((item) => <Link key={item.to} className="side-link" to={item.to} onClick={() => setOpen(false)}>{<item.icon size={17} />}<span>{item.label}</span></Link>)}</nav><div className="sidebar-user"><button type="button" onClick={runLogout}><span className="avatar">{user.name.split(' ').map((x) => x[0]).join('').slice(0, 2)}</span><span><strong>{user.name}</strong><small>{user.position}</small></span><LogOut size={15} /></button></div></aside><div className="app-main"><header className="top-header"><button className="icon-button mobile-menu" type="button" onClick={() => setOpen(true)}><Menu size={18} /></button><div className="header-title"><strong>{title}</strong><span>{subtitle}</span></div><div className="header-tools"><div className="date-time">{user.role === 'manager' ? 'Manager View' : 'Officer View'}</div><button className="button secondary" type="button" onClick={runLogout}><LogOut size={14} /> Logout</button></div></header><main className="content-area">{children}</main></div></div>
}

const managerNav = () => [{ to: '/manager/dashboard', label: 'Dashboard', icon: BarChart3 }, { to: '/manager/assignments', label: 'Assignments', icon: ClipboardList }, { to: '/manager/assignments/new', label: 'Create Assignment', icon: Plus }, { to: '/manager/officers', label: 'Officers', icon: Users }, { to: '/manager/review-queue', label: 'Review Queue', icon: ClipboardCheck }, { to: '/manager/reports', label: 'Reports', icon: FileText }, { to: '/manager/settings', label: 'Settings', icon: Settings }]
const officerNav = () => [{ to: '/officer/dashboard', label: 'My Dashboard', icon: BarChart3 }, { to: '/officer/assignments', label: 'My Assignments', icon: ClipboardList }, { to: '/officer/submissions', label: 'Submitted Reports', icon: CheckCircle2 }, { to: '/officer/corrections', label: 'Returned Corrections', icon: AlertTriangle }, { to: '/officer/profile', label: 'Profile', icon: User }]
const KPI = ({ label, value }) => <div className="stat-card"><div><div className="stat-label">{label}</div><div className="stat-value">{value}</div></div></div>

function ManagerDashboard() {
  const assignments = getAssignments(); const officers = getOfficers(); const today = new Date().toISOString().slice(0, 10)
  const inProgress = assignments.filter((a) => ['In Progress', 'On Site / Examination Ongoing', 'Report Drafting'].includes(a.status)).length
  const submitted = assignments.filter((a) => ['Submitted for Review', 'Resubmitted'].includes(a.status)).length
  const overdue = assignments.filter((a) => a.dueDate < today && !['Completed', 'Approved'].includes(a.status)).length
  const completed = assignments.filter((a) => ['Completed', 'Approved'].includes(a.status)).length
  const activeOfficerIds = new Set(assignments.map((a) => a.assignedTo))
  return <><div className="page-header"><div><h1>Manager Dashboard</h1><p>Monitor assignments, officer workload, review queues, and overdue work.</p></div></div><div className="stats-grid six-grid"><KPI label="Total Assignments" value={assignments.length} /><KPI label="In Progress" value={inProgress} /><KPI label="Submitted for Review" value={submitted} /><KPI label="Overdue" value={overdue} /><KPI label="Completed" value={completed} /><KPI label="Active Officers" value={activeOfficerIds.size} /></div><div className="dashboard-grid"><div className="main-stack"><div className="panel"><div className="panel-header"><h2>Quick Actions</h2></div><div className="page-header-actions"><Link className="button primary" to="/manager/assignments/new">Create Assignment</Link><Link className="button secondary" to="/manager/review-queue">View Review Queue</Link><Link className="button secondary" to="/manager/officers">Add Officer</Link><Link className="button secondary" to="/manager/reports">Generate Report</Link></div></div><div className="panel"><div className="panel-header"><h2>Officer Workload</h2></div><div className="table-scroll"><table><thead><tr><th>Officer</th><th>Total</th><th>In Progress</th><th>Submitted</th><th>Overdue</th><th>Completed</th></tr></thead><tbody>{officers.map((o) => { const list = assignments.filter((a) => a.assignedTo === o.id); return <tr key={o.id}><td><strong>{o.name}</strong></td><td>{list.length}</td><td>{list.filter((a) => ['In Progress', 'On Site / Examination Ongoing', 'Report Drafting'].includes(a.status)).length}</td><td>{list.filter((a) => ['Submitted for Review', 'Resubmitted'].includes(a.status)).length}</td><td>{list.filter((a) => a.dueDate < today && !['Completed', 'Approved'].includes(a.status)).length}</td><td>{list.filter((a) => ['Completed', 'Approved'].includes(a.status)).length}</td></tr> })}</tbody></table></div></div></div><aside className="right-rail"><div className="panel"><div className="panel-header"><h2>Recent Assignment Updates</h2></div>{assignments.slice(0, 6).map((a) => <div className="list-row" key={a.id}><span><strong>{a.title}</strong><small>{formatDate(a.updatedAt)} - {a.progressNote}</small></span><StatusBadge status={a.status} /></div>)}</div><div className="panel"><div className="panel-header"><h2>Assignments Requiring Attention</h2></div>{assignments.filter((a) => a.priority === 'High' || ['Overdue', 'Submitted for Review', 'Returned for Corrections'].includes(a.status) || (a.dueDate < today && !['Completed', 'Approved'].includes(a.status))).slice(0, 8).map((a) => <div className="alert-row" key={a.id}><span>{a.title}<small>{a.relatedEntity}</small></span><StatusBadge status={a.status} /></div>)}</div></aside></div></>
}

function ManagerAssignments() {
  const { showToast } = useToast(); const [search, setSearch] = useState(''); const [filter, setFilter] = useState({ officer: 'All', status: 'All' })
  const assignments = getAssignments(); const officers = getOfficers()
  const filtered = assignments.filter((a) => { const officer = officers.find((o) => o.id === a.assignedTo); const joined = `${a.title} ${a.relatedEntity} ${officer?.name || ''}`.toLowerCase(); return joined.includes(search.toLowerCase()) && (filter.officer === 'All' || a.assignedTo === filter.officer) && (filter.status === 'All' || a.status === filter.status) })
  function quickAction(item, status, message) { updateAssignment(item.id, { status }); addAssignmentUpdate(item.id, { userName: 'Demo Manager', oldStatus: item.status, newStatus: status, note: message }); showToast({ title: 'Assignment updated', message }); window.location.reload() }
  return <><div className="page-header"><div><h1>Assignments</h1><p>Search and manage assignment lifecycle across all officers.</p></div></div><div className="filter-bar"><label className="search-field"><Search size={15} /><input placeholder="Search assignments, officers, entities..." value={search} onChange={(e) => setSearch(e.target.value)} /></label><label className="select-field"><span>Officer</span><select value={filter.officer} onChange={(e) => setFilter({ ...filter, officer: e.target.value })}><option>All</option>{officers.map((o) => <option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label className="select-field"><span>Status</span><select value={filter.status} onChange={(e) => setFilter({ ...filter, status: e.target.value })}><option>All</option>{STATUS_OPTIONS.map((x) => <option key={x}>{x}</option>)}</select></label></div><div className="table-card"><div className="table-scroll"><table><thead><tr><th>Assignment</th><th>Officer</th><th>Entity</th><th>Type</th><th>Status</th><th>Priority</th><th>Due Date</th><th>Latest Update</th><th>Actions</th></tr></thead><tbody>{filtered.map((a) => { const officer = officers.find((o) => o.id === a.assignedTo); return <tr key={a.id}><td><strong>{a.title}</strong></td><td>{officer?.name || '-'}</td><td>{a.relatedEntity}</td><td>{a.assignmentType}</td><td><StatusBadge status={a.status} /></td><td>{a.priority}</td><td>{formatDate(a.dueDate)}</td><td>{a.progressNote}</td><td><div className="table-actions"><Link to={`/officer/assignments/${a.id}`} className="button secondary compact">View</Link><button className="button secondary compact" onClick={() => quickAction(a, 'Under Review', 'Marked under review.')}>Mark Under Review</button><button className="button secondary compact" onClick={() => quickAction(a, 'Approved', 'Assignment approved.')}>Approve</button><button className="button secondary compact" onClick={() => quickAction(a, 'Returned for Corrections', 'Returned for corrections.')}>Return</button></div></td></tr> })}</tbody></table></div></div></>
}

function ManagerCreateAssignment() {
  const navigate = useNavigate(); const { showToast } = useToast(); const officers = getOfficers()
  const [form, setForm] = useState({ title: '', description: '', assignedTo: officers[0]?.id || '', relatedEntity: '', assignmentType: 'Onsite Examination', priority: 'Medium', dueDate: '', notes: '', attachment: '' })
  function submit(event, asDraft = false) { event.preventDefault(); if (!asDraft && (!form.title || !form.description || !form.assignedTo || !form.dueDate)) return showToast({ title: 'Missing fields', message: 'Please complete required fields.' }); const officer = officers.find((o) => o.id === form.assignedTo); const assignment = createAssignment({ title: form.title, description: form.description, assignedTo: form.assignedTo, assignedBy: 'manager-001', relatedEntity: form.relatedEntity, assignmentType: form.assignmentType, priority: form.priority, dueDate: form.dueDate, progressNote: asDraft ? 'Saved as draft.' : 'Assignment created and assigned.', supportingNotes: form.notes, attachmentName: form.attachment, status: 'Assigned' }); addAssignmentUpdate(assignment.id, { userName: 'Demo Manager', oldStatus: '-', newStatus: 'Assigned', note: `Assignment created and assigned to ${officer?.name || 'officer'}.` }); showToast({ title: asDraft ? 'Draft saved' : 'Assignment assigned successfully.', message: asDraft ? 'Draft assignment saved.' : `Assignment created and assigned to ${officer?.name || 'officer'}.` }); navigate('/manager/assignments') }
  return <><div className="page-header"><div><h1>Create Assignment</h1><p>Assign work to an officer and define due date, priority, and instructions.</p></div></div><form className="panel form-grid" onSubmit={(e) => submit(e, false)}><label><span>Assignment Title</span><input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><label><span>Description / Instructions</span><textarea required value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><label><span>Select Officer</span><select required value={form.assignedTo} onChange={(e) => setForm({ ...form, assignedTo: e.target.value })}>{officers.map((o) => <option key={o.id} value={o.id}>{o.name} - {o.position}</option>)}</select></label><label><span>Related Entity / Institution</span><input value={form.relatedEntity} onChange={(e) => setForm({ ...form, relatedEntity: e.target.value })} /></label><label><span>Assignment Type</span><select value={form.assignmentType} onChange={(e) => setForm({ ...form, assignmentType: e.target.value })}>{ASSIGNMENT_TYPES.map((x) => <option key={x}>{x}</option>)}</select></label><label><span>Priority</span><select value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value })}>{PRIORITY_OPTIONS.map((x) => <option key={x}>{x}</option>)}</select></label><label><span>Due Date</span><input type="date" required value={form.dueDate} onChange={(e) => setForm({ ...form, dueDate: e.target.value })} /></label><label><span>Supporting Notes</span><textarea value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></label><label><span>Attachment Upload (Demo)</span><input type="file" onChange={(e) => setForm({ ...form, attachment: e.target.files?.[0]?.name || '' })} /></label>{form.attachment ? <small>Selected file: {form.attachment}</small> : null}<div className="page-header-actions"><button className="button primary" type="submit">Assign to Officer</button><button className="button secondary" type="button" onClick={(e) => submit(e, true)}>Save Draft</button><Link className="button secondary" to="/manager/assignments">Cancel</Link></div></form></>
}

function OfficerDashboard({ user }) {
  const own = getAssignmentsForOfficer(user.id); const now = new Date(); const dueSoon = own.filter((a) => { const diff = (new Date(a.dueDate).getTime() - now.getTime()) / (1000 * 60 * 60 * 24); return diff >= 0 && diff <= 7 })
  return <><div className="page-header"><div><h1>My Dashboard</h1><p>View your assigned work, deadlines, submitted reports, and returned corrections.</p></div></div><div className="stats-grid six-grid"><KPI label="My Assignments" value={own.length} /><KPI label="In Progress" value={own.filter((a) => ['In Progress', 'On Site / Examination Ongoing', 'Report Drafting'].includes(a.status)).length} /><KPI label="Due Soon" value={dueSoon.length} /><KPI label="Submitted for Review" value={own.filter((a) => ['Submitted for Review', 'Resubmitted'].includes(a.status)).length} /><KPI label="Returned for Corrections" value={own.filter((a) => a.status === 'Returned for Corrections').length} /><KPI label="Completed" value={own.filter((a) => ['Completed', 'Approved'].includes(a.status)).length} /></div><div className="dashboard-grid"><div className="main-stack"><div className="panel"><div className="panel-header"><h2>My Active Assignments</h2></div>{own.filter((a) => !['Completed', 'Approved'].includes(a.status)).map((a) => <div key={a.id} className="list-row"><span><strong>{a.title}</strong><small>{a.relatedEntity} - Due {formatDate(a.dueDate)} - {a.progressNote}</small></span><div className="page-header-actions"><StatusBadge status={a.status} /><Link className="button secondary compact" to={`/officer/assignments/${a.id}`}>Open Assignment</Link></div></div>)}</div><div className="panel"><div className="panel-header"><h2>Due Soon</h2></div>{dueSoon.length ? dueSoon.map((a) => <div className="alert-row" key={a.id}><span>{a.title}<small>{formatDate(a.dueDate)}</small></span><StatusBadge status={a.status} /></div>) : <p>No assignments due in the next 7 days.</p>}</div></div><aside className="right-rail"><div className="panel"><div className="panel-header"><h2>Returned for Corrections</h2></div>{own.filter((a) => a.status === 'Returned for Corrections').map((a) => <div key={a.id} className="alert-row"><span>{a.title}</span><Link className="button secondary compact" to={`/officer/assignments/${a.id}`}>Open</Link></div>)}</div><div className="panel"><div className="panel-header"><h2>Submitted for Review</h2></div>{own.filter((a) => ['Submitted for Review', 'Resubmitted'].includes(a.status)).map((a) => <div key={a.id} className="alert-row"><span>{a.title}</span><StatusBadge status={a.status} /></div>)}</div></aside></div></>
}

function OfficerAssignments({ user }) {
  const list = getAssignmentsForOfficer(user.id); const [search, setSearch] = useState(''); const filtered = list.filter((a) => `${a.title} ${a.relatedEntity}`.toLowerCase().includes(search.toLowerCase()))
  return <><div className="page-header"><div><h1>My Assignments</h1><p>Track and update your assigned work.</p></div></div><div className="filter-bar"><label className="search-field"><Search size={15} /><input placeholder="Search my assignments..." value={search} onChange={(e) => setSearch(e.target.value)} /></label></div><div className="table-card"><div className="table-scroll"><table><thead><tr><th>Assignment</th><th>Entity</th><th>Type</th><th>Status</th><th>Priority</th><th>Due Date</th><th>Latest Update</th><th>Action</th></tr></thead><tbody>{filtered.map((a) => <tr key={a.id}><td><strong>{a.title}</strong></td><td>{a.relatedEntity}</td><td>{a.assignmentType}</td><td><StatusBadge status={a.status} /></td><td>{a.priority}</td><td>{formatDate(a.dueDate)}</td><td>{a.progressNote}</td><td><Link className="button secondary compact" to={`/officer/assignments/${a.id}`}>View</Link></td></tr>)}</tbody></table></div></div></>
}

function OfficerAssignmentDetail({ user }) {
  const { id } = useParams(); const navigate = useNavigate(); const { showToast } = useToast()
  const [assignment, setAssignment] = useState(() => getAssignments().find((x) => x.id === id))
  const [newStatus, setNewStatus] = useState('In Progress'); const [note, setNote] = useState(''); const [attachment, setAttachment] = useState('')
  const updates = getAssignmentUpdates(id)
  if (!assignment || assignment.assignedTo !== user.id) return <div className="panel"><p>Assignment not found.</p></div>
  function submitUpdate(event) { event.preventDefault(); const updated = updateAssignment(id, { status: newStatus, progressNote: note || assignment.progressNote, attachmentName: attachment || assignment.attachmentName }); addAssignmentUpdate(id, { userName: user.name, oldStatus: assignment.status, newStatus, note: note || 'Status updated.' }); setAssignment(updated); setNote(''); showToast({ title: 'Assignment updated', message: 'Progress update saved.' }) }
  function submitForReview() { const status = 'Submitted for Review'; const updated = updateAssignment(id, { status, progressNote: note || 'Submitted for manager review.' }); addAssignmentUpdate(id, { userName: user.name, oldStatus: assignment.status, newStatus: status, note: 'Submitted for manager review.' }); setAssignment(updated); showToast({ title: 'Assignment submitted for review.', message: 'Awaiting manager review.' }); navigate('/officer/submissions') }
  return <div className="main-stack"><div className="panel"><div className="panel-header"><h2>Assignment Summary</h2></div><p><strong>{assignment.title}</strong></p><p>{assignment.description}</p><div className="metadata-row"><span>Assigned by: Demo Manager</span><span>Assigned date: {formatDate(assignment.createdAt)}</span><span>Due date: {formatDate(assignment.dueDate)}</span><span>Priority: {assignment.priority}</span><span>Entity: {assignment.relatedEntity}</span><span>Type: {assignment.assignmentType}</span><span>Status: {assignment.status}</span></div></div><div className="panel"><div className="panel-header"><h2>Progress Timeline</h2></div>{updates.length ? updates.map((u) => <div className="list-row" key={u.id}><span><strong>{u.userName}</strong><small>{formatDate(u.createdAt)} - {u.oldStatus} to {u.newStatus}</small><small>{u.note}</small></span></div>) : <p>No updates yet.</p>}</div><form className="panel form-grid" onSubmit={submitUpdate}><div className="panel-header"><h2>Update Status</h2></div><label><span>New Status</span><select value={newStatus} onChange={(e) => setNewStatus(e.target.value)}>{OFFICER_UPDATE_STATUSES.map((s) => <option key={s}>{s}</option>)}</select></label><label><span>Progress Note</span><textarea value={note} onChange={(e) => setNote(e.target.value)} /></label><label><span>Attachment Upload (Demo)</span><input type="file" onChange={(e) => setAttachment(e.target.files?.[0]?.name || '')} /></label><div className="page-header-actions"><button className="button primary" type="submit">Submit Update</button><button type="button" className="button secondary" onClick={submitForReview}>Submit for Review</button></div></form></div>
}

function ManagerReviewQueue() {
  const { showToast } = useToast(); const assignments = getAssignments(); const officers = getOfficers(); const [filter, setFilter] = useState('Submitted for Review'); const [feedback, setFeedback] = useState(''); const [selectedId, setSelectedId] = useState(''); const visible = assignments.filter((a) => (filter === 'All' ? true : a.status === filter)); const selected = assignments.find((a) => a.id === selectedId)
  function act(status) { if (!selected) return; updateAssignment(selected.id, { status, managerFeedback: feedback }); addReview({ assignmentId: selected.id, status, feedback }); addAssignmentUpdate(selected.id, { userName: 'Demo Manager', oldStatus: selected.status, newStatus: status, note: feedback || (status === 'Approved' ? 'Assignment approved.' : 'Assignment returned for corrections.') }); showToast({ title: status === 'Approved' ? 'Assignment approved.' : 'Assignment returned for corrections.', message: 'Review decision saved.' }); setSelectedId(''); setFeedback(''); window.location.reload() }
  return <><div className="page-header"><div><h1>Review Queue</h1><p>Review submitted officer work and provide decisions.</p></div></div><div className="filter-bar"><label className="select-field"><span>Status Tab</span><select value={filter} onChange={(e) => setFilter(e.target.value)}>{['Submitted for Review', 'Under Review', 'Returned for Corrections', 'Approved', 'Completed', 'All'].map((s) => <option key={s}>{s}</option>)}</select></label></div><div className="table-card"><div className="table-scroll"><table><thead><tr><th>Assignment</th><th>Officer</th><th>Entity</th><th>Submitted Date</th><th>Priority</th><th>Latest Note</th><th>Action</th></tr></thead><tbody>{visible.map((a) => <tr key={a.id}><td>{a.title}</td><td>{officers.find((o) => o.id === a.assignedTo)?.name || '-'}</td><td>{a.relatedEntity}</td><td>{formatDate(a.updatedAt)}</td><td>{a.priority}</td><td>{a.progressNote}</td><td><button className="button secondary compact" onClick={() => setSelectedId(a.id)}>Open Review</button></td></tr>)}</tbody></table></div></div>{selected ? <div className="modal-backdrop" onMouseDown={() => setSelectedId('')}><div className="modal-card" onMouseDown={(e) => e.stopPropagation()}><div className="modal-header"><h2>Open Review</h2></div><div className="modal-body"><p><strong>{selected.title}</strong></p><p>{selected.description}</p><p>Officer note: {selected.progressNote}</p><p>Attachment: {selected.attachmentName || 'No attachment uploaded (demo).'}</p><label><span>Feedback</span><textarea value={feedback} onChange={(e) => setFeedback(e.target.value)} /></label></div><div className="modal-footer"><button className="button secondary" onClick={() => act('Returned for Corrections')}>Return for Corrections</button><button className="button primary" onClick={() => act('Approved')}>Approve</button></div></div></div> : null}</>
}

function ManagerOfficers() {
  const { showToast } = useToast(); const assignments = getAssignments(); const [officers, setOfficers] = useState(getOfficers()); const [open, setOpen] = useState(false); const [form, setForm] = useState({ name: '', email: '', position: '', department: 'Compliance' })
  function saveNewOfficer(event) { event.preventDefault(); addOfficer({ id: `officer-${String(Date.now()).slice(-4)}`, ...form }); setOfficers(getOfficers()); setOpen(false); setForm({ name: '', email: '', position: '', department: 'Compliance' }); showToast({ title: 'Officer added', message: 'Officer added successfully.' }) }
  return <><div className="page-header"><div><h1>Officers</h1><p>Track officer roster and assignment workload.</p></div><button className="button primary" onClick={() => setOpen(true)}>Add New Officer</button></div><div className="table-card"><div className="table-scroll"><table><thead><tr><th>Name</th><th>Position</th><th>Email</th><th>Total</th><th>In Progress</th><th>Submitted</th><th>Overdue</th><th>Completed</th></tr></thead><tbody>{officers.map((o) => { const own = assignments.filter((a) => a.assignedTo === o.id); const today = new Date().toISOString().slice(0, 10); return <tr key={o.id}><td>{o.name}</td><td>{o.position}</td><td>{o.email}</td><td>{own.length}</td><td>{own.filter((a) => ['In Progress', 'On Site / Examination Ongoing', 'Report Drafting'].includes(a.status)).length}</td><td>{own.filter((a) => ['Submitted for Review', 'Resubmitted'].includes(a.status)).length}</td><td>{own.filter((a) => a.dueDate < today && !['Completed', 'Approved'].includes(a.status)).length}</td><td>{own.filter((a) => ['Completed', 'Approved'].includes(a.status)).length}</td></tr> })}</tbody></table></div></div>{open ? <div className="modal-backdrop" onMouseDown={() => setOpen(false)}><div className="modal-card" onMouseDown={(e) => e.stopPropagation()}><div className="modal-header"><h2>Add Officer</h2></div><form className="modal-body form-grid" onSubmit={saveNewOfficer}><label><span>Full Name</span><input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label><span>Email</span><input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label><span>Position</span><input required value={form.position} onChange={(e) => setForm({ ...form, position: e.target.value })} /></label><label><span>Department</span><input value={form.department} onChange={(e) => setForm({ ...form, department: e.target.value })} /></label><label><span>Role</span><input value="Officer" disabled /></label><div className="modal-footer"><button className="button secondary" type="button" onClick={() => setOpen(false)}>Cancel</button><button className="button primary" type="submit">Save</button></div></form></div></div> : null}</>
}

function ManagerReports() { const { showToast } = useToast(); const cards = ['Assignment Status Report', 'Officer Workload Report', 'Overdue Assignments Report', 'Submitted for Review Report', 'Completed Assignments Report']; return <><div className="page-header"><div><h1>Reports</h1><p>Generate demo reports and export interactions.</p></div></div><div className="programme-grid">{cards.map((title) => <div key={title} className="panel"><h3>{title}</h3><div className="page-header-actions"><button className="button primary" onClick={() => showToast({ title: 'Report generated', message: `${title} preview opened.` })}>Generate</button><button className="button secondary" onClick={() => showToast({ title: 'Export queued', message: `${title} PDF export simulated.` })}>Export PDF</button><button className="button secondary" onClick={() => showToast({ title: 'Export queued', message: `${title} Excel export simulated.` })}>Export Excel</button></div></div>)}</div></> }
function ManagerSettings({ onReset }) { return <><div className="page-header"><div><h1>Settings</h1><p>Demo mode configuration and workflow controls.</p></div></div><div className="main-stack"><div className="panel"><h3>Demo Mode Settings</h3><p>This demo uses simulated role-based sessions for presentation. Production deployment should use database-backed authentication, role-based authorization, audit logging, and internal server hosting.</p><button className="button secondary" onClick={onReset}>Reset Demo Data</button></div><div className="panel"><h3>User Management</h3><p>Manage officer roster and roles in this demo environment.</p></div><div className="panel"><h3>Status Workflow</h3><p>Assignment statuses follow a manager-officer review lifecycle.</p></div><div className="panel"><h3>Assignment Types</h3><p>Configured assignment categories are available in create-assignment form.</p></div><div className="panel"><h3>Security Notice</h3><p>This is a simulated environment and is not production authentication.</p></div></div></> }
function OfficerSubmissions({ user }) { const list = getAssignmentsForOfficer(user.id).filter((a) => ['Submitted for Review', 'Under Review', 'Resubmitted'].includes(a.status)); return <><div className="page-header"><div><h1>Submitted Reports</h1><p>Assignments waiting for manager review.</p></div></div><div className="table-card"><div className="table-scroll"><table><thead><tr><th>Assignment</th><th>Submitted Date</th><th>Status</th><th>Latest Note</th><th>Manager Feedback</th><th>Action</th></tr></thead><tbody>{list.map((a) => <tr key={a.id}><td>{a.title}</td><td>{formatDate(a.updatedAt)}</td><td><StatusBadge status={a.status} /></td><td>{a.progressNote}</td><td>{a.managerFeedback || '-'}</td><td><Link className="button secondary compact" to={`/officer/assignments/${a.id}`}>Open</Link></td></tr>)}</tbody></table></div></div></> }
function OfficerCorrections({ user }) { const list = getAssignmentsForOfficer(user.id).filter((a) => a.status === 'Returned for Corrections'); return <><div className="page-header"><div><h1>Returned Corrections</h1><p>Assignments returned by manager for updates.</p></div></div><div className="table-card"><div className="table-scroll"><table><thead><tr><th>Assignment</th><th>Feedback</th><th>Returned Date</th><th>Due Date</th><th>Action</th></tr></thead><tbody>{list.map((a) => <tr key={a.id}><td>{a.title}</td><td>{a.managerFeedback || 'Please revise and resubmit.'}</td><td>{formatDate(a.updatedAt)}</td><td>{formatDate(a.dueDate)}</td><td><Link className="button secondary compact" to={`/officer/assignments/${a.id}`}>Open and Resubmit</Link></td></tr>)}</tbody></table></div></div></> }
const PlaceholderPage = ({ title, subtitle }) => <div className="panel"><h2>{title}</h2><p>{subtitle}</p></div>
function ManagerRoutes({ user, setUser, onReset }) { return <AppShell user={user} onLogout={setUser} items={managerNav()} title="Manager Workspace" subtitle="Department assignment operations"><Routes><Route path="/dashboard" element={<ManagerDashboard />} /><Route path="/assignments" element={<ManagerAssignments />} /><Route path="/assignments/new" element={<ManagerCreateAssignment />} /><Route path="/officers" element={<ManagerOfficers />} /><Route path="/review-queue" element={<ManagerReviewQueue />} /><Route path="/reports" element={<ManagerReports />} /><Route path="/settings" element={<ManagerSettings onReset={onReset} />} /></Routes></AppShell> }
function OfficerRoutes({ user, setUser }) { return <AppShell user={user} onLogout={setUser} items={officerNav()} title="Officer Workspace" subtitle="My assignment execution"><Routes><Route path="/dashboard" element={<OfficerDashboard user={user} />} /><Route path="/assignments" element={<OfficerAssignments user={user} />} /><Route path="/assignments/:id" element={<OfficerAssignmentDetail user={user} />} /><Route path="/submissions" element={<OfficerSubmissions user={user} />} /><Route path="/corrections" element={<OfficerCorrections user={user} />} /><Route path="/profile" element={<PlaceholderPage title="Profile" subtitle="Officer profile details placeholder for demo." />} /></Routes></AppShell> }

function App() {
  const [user, setUser] = useState(() => getCurrentUser())
  const { showToast } = useToast()
  useEffect(() => { seedDemoData(false) }, [])
  function resetDemo() { seedDemoData(true); showToast({ title: 'Demo data reset', message: 'Seed data restored successfully.' }); window.location.reload() }
  return <Routes><Route path="/" element={<Navigate to={user ? (user.role === 'manager' ? '/manager/dashboard' : '/officer/dashboard') : '/login'} replace />} /><Route path="/login" element={user ? <Navigate to={user.role === 'manager' ? '/manager/dashboard' : '/officer/dashboard'} replace /> : <LoginPage onSignedIn={setUser} />} /><Route path="/manager/*" element={<ProtectedRoute>{user ? <ManagerRoutes user={user} setUser={setUser} onReset={resetDemo} /> : null}</ProtectedRoute>} /><Route path="/officer/*" element={<ProtectedRoute>{user ? <OfficerRoutes user={user} setUser={setUser} /> : null}</ProtectedRoute>} /><Route path="*" element={<Navigate to="/" replace />} /></Routes>
}

export default App
