/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#1A3A6B',
        primaryDeep: '#102F5D',
        teal: '#0F6E56',
        surface: '#F5F7FA',
        card: '#FFFFFF',
        border: '#E2E8F0',
        textPrimary: '#0F172A',
        textSecondary: '#64748B',
        statusGreen: '#16A34A',
        statusOrange: '#D97706',
        statusRed: '#DC2626',
        mutedBg: '#F8FAFC',
        tableRowHover: '#FAFBFF',
        tableRowBorder: '#F1F5F9',

        sidebarStart: '#0F2548',
        sidebarEnd: '#0D3060',
        white08: 'rgba(255,255,255,0.08)',

        infoBg: '#EFF6FF',
        infoBorder: '#BFDBFE',

        statusBadgeCompletedBg: '#F0FDF4',
        statusBadgeCompletedBorder: '#BBF7D0',
        statusBadgeOnTrackBg: '#EFF6FF',
        statusBadgeOnTrackText: '#1D4ED8',
        statusBadgeOnTrackBorder: '#BFDBFE',
        statusBadgeAtRiskBg: '#FFFBEB',
        statusBadgeAtRiskBorder: '#FDE68A',
        statusBadgeOverdueBg: '#FEF2F2',
        statusBadgeOverdueBorder: '#FECACA',

        typeBadgeAuditBg: '#F5F3FF',
        typeBadgeAuditText: '#7C3AED',
        typeBadgeAuditBorder: '#DDD6FE',
        typeBadgeItBg: '#EFF6FF',
        typeBadgeItText: '#2563EB',
        typeBadgeItBorder: '#BFDBFE',
        typeBadgeComplianceBg: '#FFF7ED',
        typeBadgeComplianceText: '#C2410C',
        typeBadgeComplianceBorder: '#FED7AA',
        typeBadgeInspectionBg: '#F0FDF4',
        typeBadgeInspectionText: '#166534',
        typeBadgeInspectionBorder: '#BBF7D0',
        typeBadgePolicyBg: '#FDF4FF',
        typeBadgePolicyText: '#9333EA',
        typeBadgePolicyBorder: '#E9D5FF',
        typeBadgeResearchBg: '#F0FDFA',
        typeBadgeResearchText: '#0F6E56',
        typeBadgeResearchBorder: '#99F6E4',
      },
      fontFamily: {
        heading: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        card: '10px',
        btn: '7px',
      },
      borderWidth: {
        3: '3px',
      },
    },
  },
  plugins: [],
}
